# .github/workflows/main.yml

name: Pipeline de CI - Testes da API

# Gatilho: Executa o workflow a cada push para o branch 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Nome do job
  build-and-test:
    # Máquina virtual que executará o job
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do código-fonte
      # Clona o repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v3

      # Etapa 2: Configuração do ambiente Python
      # Instala a versão especificada do Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Etapa 3: Instalação das dependências
      # Instala as bibliotecas listadas no requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Etapa 4: Execução dos testes unitários
      # Roda os testes com pytest
      - name: Executar testes com Pytest
        run: pytest